version: '3'
services:
  mongo:
    image: mongo:6
    container_name: snipsave-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    container_name: snipsave-backend
    restart: always
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=mongodb://mongo:27017/snipsave
      - JWT_SECRET=supersecret
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: snipsave-frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
volumes:
  mongo-data: